Repository vmware-tanzu/sonobuoy, pull requests merged in 2018-02, with the labels that each got.

#260 Exit with an error instead of panic
  pkg/discovery/discovery.go
  pkg/discovery/utils.go
Labels: p2 - Long-term Important

#261 Handle signals from kubernetes
  cmd/sonobuoy/app/worker.go
  pkg/plugin/aggregation/run.go
  pkg/plugin/constants.go
  pkg/plugin/driver/job/job.go
  pkg/worker/worker.go
Labels: p0 - Higher Priority

#264 Shuffles gen args back to cmd and operations to prevent dep-graph issues
  cmd/sonobuoy/app/args/image.go
  cmd/sonobuoy/app/args/namespace.go
  cmd/sonobuoy/app/gen.go
  cmd/sonobuoy/app/gen_plugin.go
  cmd/sonobuoy/app/operations/gen.go
  cmd/sonobuoy/app/operations/gen_plugin.go
  cmd/sonobuoy/app/operations/gen_plugin_test.go
  cmd/sonobuoy/app/operations/mode.go
  cmd/sonobuoy/app/operations/run.go
  cmd/sonobuoy/app/run.go
Labels: p1 - Important

#267 Adds TODO comments from walk through, lots of cleanup and shuffling
  cmd/sonobuoy/app/args.go
  cmd/sonobuoy/app/cp.go
  cmd/sonobuoy/app/gen.go
  cmd/sonobuoy/app/logs.go
  cmd/sonobuoy/app/run.go
  cmd/sonobuoy/app/status.go
  pkg/client/cp.go
  pkg/client/gen.go
  pkg/client/interfaces.go
  pkg/client/logs.go
  pkg/client/mode.go
  pkg/client/run.go
  pkg/client/status.go
  pkg/config/config.go
Labels: p1 - Important

#269 Cleanup safe Exit(0) scenarios
  cmd/sonobuoy/app/gen.go
  cmd/sonobuoy/app/master.go
  cmd/sonobuoy/app/root.go
  cmd/sonobuoy/app/run.go
  cmd/sonobuoy/app/status.go
  pkg/discovery/discovery.go
Labels: p2 - Long-term Important
