Repository vmware-tanzu/sonobuoy, pull requests merged in 2018-07, with the labels that each got.

#453 Retrieve error handling
  Gopkg.lock
  Gopkg.toml
  cmd/sonobuoy/app/retrieve.go
  pkg/client/interfaces.go
  pkg/client/retrieve.go
  vendor/golang.org/x/sync/AUTHORS
  vendor/golang.org/x/sync/CONTRIBUTORS
  vendor/golang.org/x/sync/LICENSE
  vendor/golang.org/x/sync/PATENTS
  vendor/golang.org/x/sync/errgroup/errgroup.go
Labels: requires manual verification

#474 Removes PodPresets and Secrets gathering
  pkg/config/config.go
  pkg/discovery/queries.go
Labels: p1 - Important, requires manual verification

#510 When inspecting another changeset I found our internal template to be old
  pkg/discovery/queries.go
  pkg/plugin/driver/daemonset/daemonset.go
  pkg/plugin/driver/daemonset/daemonset_test.go
  pkg/plugin/driver/daemonset/template.go
Labels: p1 - Important
